# Generated by Django 4.2.7 on 2023-12-01 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_contact_email_alter_contact_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
